### LISTAR
GET {{baseUrl}}/clientes?page=0&size=100
Content-Type: application/json
Authorization: Bearer {{token}}

### CRIAR
POST {{baseUrl}}/clientes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Maria da Silva",
  "email": "maria_silva2@email.com",
  "telefone": "49999999999",
  "tipoCliente": "VAREJO",
  "tipoPessoa": "FISICA",
  "numeroDocumento": "00055522267",
  "ativo": false,
  "enderecos": [
    {
      "cep": "89000000",
      "estado": "SP",
      "cidade": "Campinas",
      "bairro": "Monte Alegre",
      "logradouro": "Rua XV de Novembro",
      "numero": "S/N",
      "complemento": "casa 03",
      "pontoReferencia": "Próximo Praça da Luz",
      "observacoes": "Entregar preferencialmente pela manhã",
      "enderecoPrincipal": true,
      "tipoEndereco": "ENTREGA",
      "apelido": "Minha casa"
    },
    {
      "cep": "89000000",
      "estado": "SP",
      "cidade": "Campinas",
      "bairro": "Monte Alegre",
      "logradouro": "Rua XV de Novembro",
      "numero": "S/N",
      "complemento": "casa 03",
      "pontoReferencia": "Próximo Praça da Luz",
      "observacoes": "Entregar preferencialmente pela manhã",
      "enderecoPrincipal": false,
      "tipoEndereco": "ENTREGA",
      "apelido": "Minha casa"
    }
  ]
}

### BUSCAR
GET {{baseUrl}}/clientes/1

### ATUALIZAR
PUT {{baseUrl}}/clientes/1
Content-Type: application/json

{
  "nome": "Maria da Silva",
  "email": "maria_silva@email.com",
  "telefone": "49999999999",
  "tipoCliente": "VAREJO",
  "tipoPessoa": "FISICA",
  "numeroDocumento": "00055522266",
  "ativo": true,
  "enderecos": [
    {
      "cep": "89000000",
      "estado": "SP",
      "cidade": "Campinas",
      "bairro": "Monte Alegre",
      "logradouro": "Rua XV de Novembro",
      "numero": "S/N",
      "complemento": "casa 03",
      "pontoReferencia": "Próximo Praça da Luz",
      "observacoes": "Entregar preferencialmente pela manhã",
      "enderecoPrincipal": true,
      "tipoEndereco": "ENTREGA",
      "apelido": "Minha casa"
    }
  ]
}

### DELETE
DELETE {{baseUrl}}/clientes/1


### LISTAR ENDERECOS
GET {{baseUrl}}/clientes/{{clienteId}}/enderecos

### CRIAR ENDERECO
POST {{baseUrl}}/clientes/{{clienteId}}/enderecos
Content-Type: application/json

{
  "cep": "88000000",
  "estado": "SC",
  "cidade": "Florianopolis",
  "bairro": "Centro",
  "logradouro": "Rua A",
  "numero": "123",
  "tipoEndereco": "ENTREGA",
  "apelido": "Casa"
}

### ATUALIZAR
PUT {{baseUrl}}/clientes/{{clienteId}}/enderecos/{{enderecoId}}
Content-Type: application/json

{
  "cep": "88000000",
  "estado": "SC",
  "cidade": "Florianopolis",
  "bairro": "Centro",
  "logradouro": "Rua B",
  "numero": "456",
  "tipoEndereco": "ENTREGA",
  "apelido": "Casa Edit"
}

### DELETE
DELETE {{baseUrl}}/clientes/{{clienteId}}/enderecos/{{enderecoId}}