# Dados configuracao JPA
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Configuracao do cliente web do banco h2
spring.h2.console.enabled=false

# Configuracao do servidor
server.error.include-message=always

# Configuracao do Swagger
springdoc.api-docs.path=/api-fabricapins
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Configuracao do Render
server.port=${PORT:8080}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized
management.endpoint.health.roles=ADMIN

# Configuração de CORS
app.cors.allowed-origins = https://afabricadepins.com.br
