# ================================
# GERA SCRIPT SQL PARA CRIACAO DO BANCO DE DADOS
#spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql
#spring.jpa.properties.hibernate.hbm2ddl.delimiter=;


# Dados de conexao com o banco H2
spring.datasource.url=jdbc:h2:mem:fabricapins;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always

# Dados configuracao JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracao do cliente web do banco h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracao do servidor
server.error.include-message=always

# Configuracao do Swagger
springdoc.api-docs.path=/api-fabricapins
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Configuracao do Render
server.port=${PORT:8080}

# Configuração de CORS
app.cors.allowed-origins = http://localhost:3000,http://localhost:5173

#Logger
#logging.level.org.hibernate=DEBUG
#logging.level.org.springframework.orm.jpa=DEBUG



